apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.cache.image }}
        ports:
        - containerPort: 8080
        - containerPort: 9092
        volumeMounts:
          - name: data
            mountPath: /mnt/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bazel-cache-data
